### PR TITLE
Reorganization of modules and files

### PR DESCRIPTION
**Pull request by wodeni**
# Description

This PR reorganizes the Haskell package structure and the files in the repo. Key changes include:

* Add a namespace to all Penrose modules: `Penrose.*`. I intentionally avoided hierarchical namespaces for readability, but let me know if you have other opinions.
* Enforce module exports to ensure modularity and readability of individual modules
* Specifying modules that are automatically generated in `penrose.cabal`, particularly `SubstanceTokenizer`, which prevents our old `mkdoc.sh` script from generating documentation properly
* Extract the Main module from the library build process and build it separately
* Renamed `Interface` to `Penrose.API`
* Enable `stack haddock` to build documentation
* Bump the package version and adding `--version` to `penrose` binary 
* Added `hlint` and `stylish-haskell` configuration files for better styling of source code
* Cleaning up `src`: 
  * All existing examples are now in `examples` instead of `src`
  * Deprecated old programs in `sub` and `sty` and moved the functional examples to `examples/*-domain` folders. Old programs are in `examples/archive`
  * Now developers are expected to run `penrose` inside `examples` to avoid path issues
  * For this and organizational purposes, `plugins` are also moved to `examples`
  * `react-renderer` now lives in `TOP`

# Implementation strategy and design decisions

* The new package structure resembles popular Haskell packages such as [pandoc](https://github.com/jgm/pandoc), which generates exe + lib as well.
* Better structure and module exports hopefully can provide better guidelines for people to write more modular code and better documentation.
* If we want to allow others to build other tools using the backend, the new structure allows documentation to be automatically built and uploaded to platforms such as Hackage.

# Examples with steps to reproduce them

* `stack haddock` for documentation
* `stack build` to see the new build process

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [x] My changes generate no new warnings
- [x] New and existing tests pass locally using `stack test`
- [x] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

### CODE REVIEW

**Comment by wodeni** [comment]
cc @maxkrieger for feedback about docker and changing the location of `react-renderer`
cc @hypotext for Haskell related changes.

**Comment by hypotext** [comment]
@wodeni I'll take a look this weekend. Let me know if there's anything in particular you want me to review.

**Comment by wodeni** [comment]
> @wodeni I'll take a look this weekend. Let me know if there's anything in particular you want me to review.

Probably the best way to review this is just to pull, build, and try to use it. You can go over the PR description and let me know if you would like any additional changes. This PR aims to achieve a more stable organization of things from now on.

**Comment by hypotext** [comment]
Thanks for doing the reorg! I went through a couple of steps and wasn't able to create a diagram in the frontend. Seems like there's a serialization error in the backend. Here are my steps:

Pulled from docs on separate branch
`stack upgrade` (worked)
`stack build --profile` (worked)
`stack haddock` (worked)
frontend in `penrose2/react-renderer`: `sudo npm install`, then I got a bunch of npm/node errors, so I updated npm, and eventually I seemed to be able to run `npm run build-lib` and `npm start` fine (it says "compiled successfully")
try running Penrose on a couple of examples from `examples/`
when opening the frontend in the browser, I get a blank screen, and when I hit autostep, I get the error `Unhandled Rejection (TypeError): Cannot read property 'map' of undefined` (and it's the only thing that's logged in the console)

image

---

Separately, we should update the wiki after this branch is merged to document where the examples are located, and where to run Penrose from.

Also, it seems a little unexpected that our Haddock build documents all our dependencies but not Penrose itself!

**Comment by maxkrieger** [comment]
Can't get to my laptop right now but `sudo npm install` should be `npm
install`, sudo is only needed for global modules

**Comment by wodeni** [comment]
> Separately, we should update the wiki after this branch is merged to document where the examples are located, and where to run Penrose from.

Will do after this PR is merged :D.

> Also, it seems a little unexpected that our Haddock build documents all our dependencies but not Penrose itself!

Shouldn't be happening now. Before this reorg, we defined the entire Haskell project with a singular executable target. Haddock does not generate documentation for exes. Now that we have a separate library target, it does.

It seems that you need to run `npm install` first in `react-renderer`. Let @maxkrieger and I know if anything unexpected happens.

**Comment by hypotext** [comment]
Hey! So I tried a bunch of stuff and ran into the same error in the end. Here's what I tried (btw, I'm on macOS Mojave):

* uninstalling and reinstalling node (most recent, via homebrew) -- kept running into [node-gyp errors](https://github.com/nodejs/node-gyp/issues/809)
* removing `package-lock.json`, `node_modules`, and `~/.node_gyp`
* restarting computer
* downgrading node from v12 to v10.16.0 by using nvm (which incidentally only works in bash) -- fixed my fsevents/node_gyp error so it could use the prebuilt binary per this issue https://github.com/fsevents/fsevents/issues/246 -- so `npm install` says it ran without error
* did `npm run build-lib` and `npm start` (which say they both ran successfully) in `penrose/react-renderer`

After that, I did `runpenrose2 real-analysis-domain/spec-RA.sub real-analysis-domain/perpendicular-RA.sty real-analysis-domain/real-analysis.dsl` in `examples`, then went to `localhost:3000`, which gives me the same error, `Unhandled Rejection (TypeError): Cannot read property 'map' of undefined` (see more detailed error in prev comment). 

So, I still can't repro this PR due to a frontend build issue. Sorry!

**Comment by maxkrieger** [comment]
Ahhh I'm sorry this is happening!
The only thing I can't rule out is the backend -- what does your
`runpenrose2` output without any args? Just to make sure it's the latest
build. The stack build will emit a binary in a different path than before
because it's a new LTS version. This was changed during #236. I had to deal
with that particular problem on my machine.

**Comment by wodeni** [comment]
@maxkrieger good point. @hypotext you can even try running `penrose --version`. The current version number is `0.1.1.1`.

**Comment by hypotext** [comment]
That did it, thanks @maxkrieger! Now I can compile a diagram. Y'all should feel free to move forward with merging this PR.

Unfortunately, my intero install seems to have broken too, because it can't compile `GhciTypes`.  I'll look into fixing that later.

**Comment by wodeni** [comment]
> That did it, thanks @maxkrieger! Now I can compile a diagram. Y'all should feel free to move forward with merging this PR.
> 
> Unfortunately, my intero install seems to have broken too, because it can't compile `GhciTypes`. I'll look into fixing that later.

This happened to me repeatedly. Now I just have a global installation of intero, which works fine with my VSCode plugin. The root cause of the issue seems to be some version mismatches in the dependencies (e.g. `directory`). For now I'll go ahead and merge the PR.

**Comment by hypotext** [comment]
@wodeni Can you give me more info about how you fixed intero? I'm trying now, so I just uninstalled and reinstalled intero, then run into some pretty weird dylib errors that seem specific to Mac + emacs.

**Pull request merged**
