### PR TITLE
Raytracing domain

### PR DESCRIPTION
**Pull request by wodeni**
# Description

This PR contains the implementation of the raytracing domain for Penrose, along with a plugin for string generation from regexes. 

Related issues: none

# TODOs

## High-level objectives

Target diagrams:

- [x] Generate a matching regex expansion
- [x] Use the canvas size to parametrize scene geometry generation
- (optional) Show several sampled ray paths in the diagram
- (optional) Allow multiple paths in a scene
- (optional) Disallow non-sensical consecutive diffuse bounces
## Lower-level objectives

- [ ] Send "user-agent" that includes the canvas size to the backend upon connection (?)
- [x] Change the plugin to limit the length of regex expansion given canvas size
- [ ] Show normals to surfaces at points of intersection
- [ ] Show angles of reflection
- [x] SVG imports for mirrors and eye/camera
- [x] Fix arrow rendering by making the start of it to be the tip of arrowhead
- [x] functions for vertex placement
  - [x] `pointOn` for placing points on rectangle
  - [x] comp fns with offsets for specular and diffuse objects
- [x] mirror rotation angle computation

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them
__ordered from newer to older examples__

- Images imported for both the camera and mirrors: 
image

- Disjoint functions make sure scene geometries do not overlap with light paths:
raytra-disjoint

- Multiple specular objects example with a rather naive way to generate `Hit` statements: assuming there's a one-to-one relationship between a specular vectex and a specular object. In other words, a path cannot bounce off from the same mirror twice:
image
- Fixed arrow renderer such that it starts exactly at `startx` and `starty`, thereby allowing more accurate rendering at bounce points:
image
- Mirror locations are adjusted similar to how angles are computed (based on normal vector):
image
- Mirror angles are now adjusted properly:
image
- Added constraints for vertex placements on diffuse objects (the "room" in this case)
image
- A very early example where diffuse hits and vertex locations are not optimized yet:
` penrose raytracing-domain/spec-raytra.sub  raytracing-domain/raytracing.sty raytracing-domain/raytracing.dsl`
image

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

- Evaluator: recursive expressions such as `override value = value + 1` is not supported. This occured when we attempted to re-compute mirror locations.

### CODE REVIEW

**Comment by wodeni** [comment]
The disjoint functions are behaving pretty well. Here's an example with `LDS*E`:
raytra-samples

**Comment by hypotext** [comment]
Looks great! 

Btw, it looks like the path going into the camera is missing an arrowhead (or it's occluded by the circle).

**Comment by wodeni** [comment]
Image import now works for the camera, with correct rotation transform:

image

**Comment by wodeni** [comment]
TODOs from diagram critique:

- [ ] Remove `Scene` type, or allow multiple scenes
- [ ] Change regex strings to constants
- [ ] `Path -> PathType`
- [ ] `PathSample -> Path`
- [ ] `SceneSatisfies -> SceneHasPathTypes`
- [ ] Thicker path segments (1.2 ~ 1.3x) / change the path color from yellow to a slightly richer yellow-orange
- [ ] Replace light source shape with "fun" icons
- [ ] add different diffuse glyphs

**Comment by wodeni** [comment]
Started to add multiple paths to the scene like the following Substance program:
```
PathType t1, t2, t3
HasForm(t1, "L(D|S)SE")
HasForm(t2, "LSDE")
HasForm(t3, "LE")

Path p1, p2, p3
p1 := Sample(t1)
p2 := Sample(t2)
p3 := Sample(t3)

AutoLabel All
``` 

It's certainly possible, but the optimizer seems to struggle to find nice-looking solutions. Here's one reasonable sample:

image

Colors are per `PathType` and completely random. I will try generating more harmonious palettes soon.

**Comment by hypotext** [comment]
Hey @wodeni, what do you think about the status of this branch? How close is it to being able to merge to master? It would be great to get it in soon. 

I'd also like to grab some of the new objectives/constraints from this branch to use in other domains, but can add them individually as well.

**Comment by keenancrane** [comment]
Just a small thing here: I notice that the lines along rays stick out slightly past the arrowheads.

**Comment by hypotext** [comment]
Hey @wodeni just bumping this PR. Will it be ready to merge soon? Let me know if there are any issues.

**Comment by wodeni** [comment]
> Hey @wodeni just bumping this PR. Will it be ready to merge soon? Let me know if there are any issues.

I made sure that this is ready to merge after the paper submission. Looks like some tests are failing. I'll look into this before actually merging.

**Comment by wodeni** [comment]
Fixed the headless test error and merged.

**Comment by hypotext** [comment]
Awesome, thanks! Great to have everything merged now.

**Pull request merged**
