### PR TITLE
feat: PathString GPI

### PR DESCRIPTION
**Pull request by maxkrieger**
I added a `PathString` GPI.~~ It's not quite ready to merge because something's broken in the `mod` tab.~~ Fixed! I also need to document it in the wiki (?).

```ts
shapeType: "PathString",
  properties: {
    center: ["VectorV", vectorSampler],
    w: ["FloatV", widthSampler],
    h: ["FloatV", heightSampler],
    rotation: ["FloatV", () => constValue("FloatV", 0)],
    opacity: ["FloatV", () => constValue("FloatV", 1.0)],
    strokeWidth: ["FloatV", strokeSampler],
    strokeStyle: ["StrV", () => constValue("StrV", "solid")],
    strokeColor: ["ColorV", colorSampler],
    color: ["ColorV", colorSampler],
    name: ["StrV", () => constValue("StrV", "defaultPolygon")],
    data: ["StrV", () => constValue("StrV", DEFAULT_PATHSTR)],
    viewBox: ["StrV", () => constValue("StrV", "0 0 100 100")],
  },
  positionalProps: ["center"],
```

It renders any SVG path you want:

```
forall PathString p {
    p.icon = PathString {
        w: 300
        h: 300
        data: "M 10 80 C 40 10, 65 10, 95 80 S 150 150, 180 80"
        viewBox: "0 0 200 200"
    }
}
```

image

### CODE REVIEW

**Comment by wodeni** [comment]
What's the status of this branch? Domain expert study participants will probably want to use this feature very soon. 

p.s.: some autodiff-able way to template these strings might be useful. Not sure exactly how it'll be implemented yet. Lmk if you have any thoughts.

**Comment by maxkrieger** [comment]
Can we cover it briefly tomorrow?

**Comment by maxkrieger** [comment]
> What's the status of this branch? Domain expert study participants will probably want to use this feature very soon.
> 
> p.s.: some autodiff-able way to template these strings might be useful. Not sure exactly how it'll be implemented yet. Lmk if you have any thoughts.

We can merge for now, it's just not documented and for whatever reason doesn't work with the mod tab.

**Comment by maxkrieger** [comment]
@wodeni this is ready

**Review by wodeni — APPROVED** [review]
Looks good! 

Note to myself: I'll need to add my drag handlers from the other PR.

**Pull request merged**
