### PR TITLE
chore: update team list

### PR DESCRIPTION
**Pull request by joshsunshine**
This PR updates the team list, sorts the team members, and updates URLs for some team members

### CODE REVIEW

**Review by samestep — APPROVED** [review]
LGTM, thanks Josh!

> sorts the team members

by what exactly?

**Comment by joshsunshine** [comment]
@samestep I sorted the former team members alphabetically.

**Comment by samestep** [comment]
@joshsunshine oh gotcha; wouldn't it be like this instead, then?

```
- [Jonathan Aldrich](https://www.cs.cmu.edu/~aldrich/)
- [Matt Davis](https://cmumatt.github.io/)
- [Rain Du](https://miyehn.me/)
- [Max Krieger](https://a9.io/)
- [Josh Pollock](https://joshmpollock.com/)
- [Dor Ma'ayan](http://www.cs.technion.ac.il/people/dorma10/)
- [Will Rinkoff](https://dsm0.github.io/)
- [Lily Shellhammer](https://www.linkedin.com/in/lily-shellhammer-899b43105)
- [Mia Tang](https://mia-tang.com/#/)
- [Stella Trout](https://github.com/strout18)
- [Jenna Wise](https://www.cs.cmu.edu/~jlwise/)
- [Helena Yang](https://heleaf.me/)
- [Kai Ye](https://www.linkedin.com/in/kai-ye-83946725a/)
```

**Comment by joshsunshine** [comment]
Yes, it would :flushed:

**Comment by samestep** [comment]
OK! Fixed in #1547.

**Pull request merged**
