### PR TITLE
Porting the compilation pipeline

### PR DESCRIPTION
**Pull request by wodeni**
# Description

⚠️ __DNR: Do Not Rebase__ ⚠️ 

Related issues: #336 #428  

We will port the Domain, Substance Style parsers/checkers and compiler into TypeScript.

# Implementation strategy and design decisions

* AST types are converted to TS. See `penrose-web/src/compiler/Style.ts` for a possible place to put the Style compiler code. The top-level function should be `compileStyle`, and its signature looks like something like this: 
```ts
export const compileStyle = (
  env: VarEnv,
  subAST: SubProg,
  styAST: StyProg
) /* :State */ => {
  // TODO: fill in the style compiler here
};

``` 
# Examples with steps to reproduce them

TODO

# Checklist

TODO: update checklist for TS

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `npm test`
- [ ] I ran `npm run docs` and there were no errors when generating the HTML site
- [ ] My code follows the style guidelines of this project (e.g.: no ESLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

### CODE REVIEW

**Comment by wodeni** [comment]
Summarizing the plan for this branch:

@hypotext and I will separately branch off from `style-compiler`, working on the compiler and the parser. We may clean up our own feature branches before merging them onto this branch when we get working versions of both components. From then on, we collaboratively work on `style-compiler` together and will __not__ alter the history of this branch again. The final merge onto `master` will be a merge commit instead of squash & merge.

**Comment by wodeni** [comment]
Just merged the new parser. I expect some experimentation when porting the Style compiler early on. I'd suggest staying on your branch until it's stable (e.g. compiles 1+ programs in our wiki) @hypotext

**Comment by hypotext** [comment]
Ok, thanks, will do! @wodeni

**Comment by wodeni** [comment]
Addressed both #436 and #437 on this branch. Feel free to pull them from your branch @hypotext

**Comment by wodeni** [comment]
Ported the domain parser (#441). I'll leave that branch up until I finish porting the semantic checker. Once I get there, we'll have a (potentially revised) `VarEnv` type, and @hypotext can review it and see if the Style compiler can work with it.

**Comment by wodeni** [comment]
Substance parser and typechecker are both ported and tested with 102 test cases 🎉 . Next step: finish Style compiler and the port should be done!

**Pull request merged**
