### PR TITLE
Serialization of backend state

### PR DESCRIPTION
**Pull request by wodeni**
# Description

I refactored the backend code base to support serialization of `State` and all other related types (e.g. `Translation`). 

Related issues: #212 #166 #213 #116 

## TODOs before merging

- [x] revert JSON tests
- [x] re-profile the system
- [x] run more examples to make sure everything works well

# Implementation strategy and design decisions

- Removed `overallObjFn` that was previously stored in `State` and wrote `evalEnergy` to evaluate the overall objective function
- Monomorphized everything else in `State`
- Rewrote `BfgsParams` such that it contains lists of `Double`s instead of hmatrix's vectors
- Replaced `Float` with `Double` everywhere in the system to get better precision per the [Haskell wiki](https://wiki.haskell.org/Performance/Floating_point)'s suggestion.

# Examples with steps to reproduce them

All examples listed in the gallery of the IDE are tested.

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [x] My changes generate no new warnings
- [x] New and existing tests pass locally using `stack test`
- [x] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

Remaining TODOs will be addressed in the PR for `interface`:
- [ ] port policy code
- [ ] clean up optimizer module
- [ ] (optional) re-format all source files with `stylish-haskell`

### CODE REVIEW

**Comment by wodeni** [comment]
Since this PR makes some changes that possibly influence the performance of the system, I profiled the system with some simple improvements:

* Base case on df8d06c0b409eb7d23215d1c4498650db8ad9b2d:
```
    Mon Jun 17 20:40 2019 Time and Allocation Profiling Report  (Final)
       penrose +RTS -p -RTS sub/tree.sub sty/venn.sty set-theory-domain/setTheory.dsl
    total time  =       36.16 secs   (36161 ticks @ 1000 us, 1 processor)
    total alloc = 28,926,000,448 bytes  (excludes profiling overheads)
COST CENTRE                    MODULE        SRC                                     %time %alloc
computedProperties             Shapes        src/Shapes.hs:(273,1)-(295,33)           57.1   66.4
showsPrec                      GenOptProblem src/GenOptProblem.hs:104:12-15            5.1    9.2
evalExpr.argResult             GenOptProblem src/GenOptProblem.hs:(603,11)-(692,90)    3.6    0.9
lookupField                    Style         src/Style.hs:(1524,1)-(1533,28)           2.9    0.4
tro                            Optimizer     src/Optimizer.hs:89:1-57                  2.8    3.0
evalGPI_withUpdate.(...)       GenOptProblem src/GenOptProblem.hs:592:13-126           2.2    3.6
lookupPropertyWithVarying      GenOptProblem src/GenOptProblem.hs:(346,1)-(349,100)    1.7    0.5
compare                        Style         src/Style.hs:176:35-37                    1.7    0.0
evalGPI_withUpdate.properties' GenOptProblem src/GenOptProblem.hs:593:13-50            1.6    1.2
lookupProperty                 GenOptProblem src/GenOptProblem.hs:(352,1)-(369,27)     1.4    0.1
evalProperty.(...)             GenOptProblem src/GenOptProblem.hs:580:9-64             1.3    3.7
stepWithObjective              Optimizer     src/Optimizer.hs:(237,1)-(267,45)         1.1    2.4
```

* Visually faster with `computedProperties` commented out:

```
    Mon Jun 17 20:47 2019 Time and Allocation Profiling Report  (Final)
       penrose +RTS -p -RTS sub/tree.sub sty/venn.sty set-theory-domain/setTheory.dsl
    total time  =       11.76 secs   (11760 ticks @ 1000 us, 1 processor)
    total alloc = 8,737,102,248 bytes  (excludes profiling overheads)
COST CENTRE                    MODULE                      SRC                                                  %time %alloc
showsPrec                      GenOptProblem               src/GenOptProblem.hs:104:12-15                        16.0   30.6
tro                            Optimizer                   src/Optimizer.hs:89:1-57                               9.4    9.8
evalGPI_withUpdate.(...)       GenOptProblem               src/GenOptProblem.hs:592:13-126                        5.1   12.0
compare                        Style                       src/Style.hs:176:35-37                                 4.6    0.0
lookupPropertyWithVarying      GenOptProblem               src/GenOptProblem.hs:(346,1)-(349,100)                 4.2    1.7
evalGPI_withUpdate.properties' GenOptProblem               src/GenOptProblem.hs:593:13-50                         4.2    4.1
stepWithObjective              Optimizer                   src/Optimizer.hs:(237,1)-(267,45)                      3.8    7.8
lookupField                    Style                       src/Style.hs:(1524,1)-(1533,28)                        3.7    0.6
lookupProperty                 GenOptProblem               src/GenOptProblem.hs:(352,1)-(369,27)                  3.3    0.2
evalExpr.argResult             GenOptProblem               src/GenOptProblem.hs:(603,11)-(692,90)                 2.4    1.9
compare                        Style                       src/Style.hs:150:25-27                                 2.2    0.0
evalProperty.(...)             GenOptProblem               src/GenOptProblem.hs:580:9-64                          2.1    5.0
evalProperty                   GenOptProblem               src/GenOptProblem.hs:(578,1)-(584,73)                  1.4    1.1
binary                         Numeric.AD.Internal.Reverse src/Numeric/AD/Internal/Reverse.hs:(182,3)-(191,89)    1.3    0.9
evalFnArgs                     GenOptProblem               src/GenOptProblem.hs:(714,1)-(718,34)                  1.1    2.3
gToJSON                        Data.Aeson.Types.ToJSON     Data/Aeson/Types/ToJSON.hs:700:5-35                    0.9    1.0
shapeExprsToVals.properties'   GenOptProblem               src/GenOptProblem.hs:387:15-50                         0.6    1.0
```

* Visually significantly (10x+) faster when `debug*=False`. `tree.sub`, `nested.sub`, and `parallel-RA.sub` all converged in ~1s.

```
    Mon Jun 17 20:55 2019 Time and Allocation Profiling Report  (Final)
       penrose +RTS -p -RTS sub/nested.sub sty/venn.sty set-theory-domain/setTheory.dsl
    total time  =       12.29 secs   (12288 ticks @ 1000 us, 1 processor)
    total alloc = 9,646,703,304 bytes  (excludes profiling overheads)
COST CENTRE                    MODULE                      SRC                                                  %time %alloc
compare                        Style                       src/Style.hs:176:35-37                                 7.9    0.0
evalGPI_withUpdate.(...)       GenOptProblem               src/GenOptProblem.hs:592:13-126                        6.7   22.6
lookupPropertyWithVarying      GenOptProblem               src/GenOptProblem.hs:(346,1)-(349,100)                 6.5    3.2
evalGPI_withUpdate.properties' GenOptProblem               src/GenOptProblem.hs:593:13-50                         6.0    7.9
lookupField                    Style                       src/Style.hs:(1524,1)-(1533,28)                        5.8    1.1
lookupProperty                 GenOptProblem               src/GenOptProblem.hs:(352,1)-(369,27)                  5.1    0.5
compare                        Style                       src/Style.hs:150:25-27                                 3.7    0.0
evalExpr.argResult             GenOptProblem               src/GenOptProblem.hs:(603,11)-(692,90)                 2.6    3.6
evalProperty.(...)             GenOptProblem               src/GenOptProblem.hs:580:9-64                          2.3    9.4
gToJSON                        Data.Aeson.Types.ToJSON     Data/Aeson/Types/ToJSON.hs:700:5-35                    2.1    2.4
evalProperty                   GenOptProblem               src/GenOptProblem.hs:(578,1)-(584,73)                  2.0    2.1
compare                        Style                       src/Style.hs:1110:25-27                                1.8    0.0
binary                         Numeric.AD.Internal.Reverse src/Numeric/AD/Internal/Reverse.hs:(182,3)-(191,89)    1.8    2.1
gToJSON                        Data.Aeson.Types.ToJSON     Data/Aeson/Types/ToJSON.hs:657:5-50                    1.3    1.3
objFuncDict                    Functions                   src/Functions.hs:(230,1)-(297,5)                       1.2    0.7
evalFnArgs                     GenOptProblem               src/GenOptProblem.hs:(714,1)-(718,34)                  1.1    4.1
unquoted                       Data.Aeson.Encoding.Builder Data/Aeson/Encoding/Builder.hs:118:1-47                1.1    1.6
shapeExprsToVals.properties'   GenOptProblem               src/GenOptProblem.hs:387:15-50                         0.9    2.0
evalExpr                       GenOptProblem               src/GenOptProblem.hs:(599,1)-(692,90)                  0.8    1.7
castTranslation.castFieldExpr  GenOptProblem               src/GenOptProblem.hs:(1033,9)-(1036,61)                0.8    1.4
evalExprs.evalExprF            GenOptProblem               src/GenOptProblem.hs:(707,11)-(709,58)                 0.4    1.1
castTranslation.castTagExpr    GenOptProblem               src/GenOptProblem.hs:(1039,9)-(1055,35)                0.4    1.1
evalExprs.evalExprF.(...)      GenOptProblem               src/GenOptProblem.hs:708:28-88                         0.4    1.2
```

**Comment by hypotext** [comment]
Thanks for the writeup! Some thoughts:

* Wow, `computedProperties` incurs that large of a performance hit if we're not using the transforms/polygons? It seems weird to me that a Map lookup (in a constant-size map) would cause this. I should fix whatever's causing this.
* It definitely looks like console IO is incurring a big cost. I don't know what `showsPrec` is. Is it just complaining about BfgsParams being printed? [L104](https://github.com/penrose/penrose/blob/serialization/src/GenOptProblem.hs#L104)
  * Maybe the big cost of console IO is another reason to surface the opt debug info in the frontend? It would be nice to figure out if the main perf cost is the string conversion or the logging itself. I suspect it's the latter, in which case, frontend support would be extra nice.
* Ideally we would profile headless w/o user input so we could gather precise timing data *and* we could run the the example to convergence over several samples (since timing can really depend on your initial state). I think headless profiling is possible if we just wait for the label/image sizes for the frontend. Not a huge priority, but nice if it's easy to do.

**Comment by joshsunshine** [comment]
Looks good. Try compressing the serialized state.

**Comment by wodeni** [comment]
> * It definitely looks like console IO is incurring a big cost. I don't know what `showsPrec` is. Is it just complaining about BfgsParams being printed? [L104](https://github.com/penrose/penrose/blob/serialization/src/GenOptProblem.hs#L104)
It's a derived function in [Text.Show](http://hackage.haskell.org/package/base-4.12.0.0/docs/Text-Show.html), and yes. 
  
>   * Maybe the big cost of console IO is another reason to surface the opt debug info in the frontend? It would be nice to figure out if the main perf cost is the string conversion or the logging itself. I suspect it's the latter, in which case, frontend support would be extra nice.
Agreed. This will be much easier now that `State` is serializable. 

> * Ideally we would profile headless w/o user input so we could gather precise timing data _and_ we could run the the example to convergence over several samples (since timing can really depend on your initial state). I think headless profiling is possible if we just wait for the label/image sizes for the frontend. Not a huge priority, but nice if it's easy to do.
This coincides with one of our TODO items:
- [ ] write a top-level function that optimizes until convergence

> As you said, It looks like the next biggest cost is the evaluator. I don't think there's laziness in Style—the functions in Style are showing up in the report because they are really being called at runtime. The `compare` function is needed for Map lookup for Sub vars, and I moved `lookupField` to Style for an organizational reason (it's mostly a runtime function).
After looking at the Style functions, I would agree with you. I'll look through the evaluator for obvious perf improvements.

**Comment by hypotext** [comment]
All sounds good. Happy to further discuss these action items if needed:

* surfacing the opt debug info in the frontend
* writing a top level function that optimizes until convergence.

**Comment by wodeni** [comment]
I completed the PR description. Since this branch is stable when running with the IDE, we decided to merge it on `master` now instead of `lsp`, which will be a longer-living development branch for more  IDE features.

**Comment by wodeni** [comment]
> All sounds good. Happy to further discuss these action items if needed: * surfacing the opt debug info in the frontend * writing a top level function that optimizes until convergence.

We can certainly discuss problem 1. #236 resolves item 2 already with `stepUntilConvergence` (still need to test it with a refactored frontend to double-check).

**Pull request merged**
