### PR TITLE
chore: add Prettier to project

### PR DESCRIPTION
**Pull request by wodeni**
# Description

[Prettier](https://prettier.io/) enforces consistent code style in the whole monorepo. I added some basic configuration files and included `yarn format` for formatting the whole repo. 

# Implementation strategy and design decisions

* Add `prettier` to root
* Add `prettier-quick` to root and include it in precommit script

# Examples with steps to reproduce them

* Run `yarn format` to manually format the entire repo
* When you commit, `prettier-quick` will format all __staged__ files.

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass locally using `npm test`
- [x] I ran `npm run docs` and there were no errors when generating the HTML site
- [x] My code follows the style guidelines of this project (e.g.: no ESLint warnings)

# Open questions

None.

### CODE REVIEW

**Comment by wodeni** [comment]
Thinking about using [lint-staged](https://www.npmjs.com/package/lint-staged) if we want auto-formatting pre-commit. Any opinion on it?

**Comment by maxkrieger** [comment]
Not a bad idea, I've seen formatting precommit done before. As long as it's not slow.

**Comment by wodeni** [comment]
It's okay. I'll try out https://prettier.io/docs/en/precommit.html#option-2-pretty-quickhttpsgithubcomazzpretty-quick instead of lint-staged, as the latter is a little too heavy for now

**Comment by wodeni** [comment]
Looking good. Merging now.

image

**Pull request merged**
