### PR TITLE
Server-side rendering of diagrams

### PR DESCRIPTION
**Pull request by wodeni**
# Description

Related issues: #292 #299 

As a step towards "batch-mode" Penrose, we developed a command-line version of the renderer. This new module, tentatively named `automator`, is a node program that compiles, optimizes, and renders a trio of Penrose programs and outputs a static SVG file. 

# Implementation strategy and design decisions

* Overall goal: communicate with the backend without the websocket connection and render output SVG without the browser
* Penrose binary now has a new command: `penrose runAPI`, which takes a JSON input from stdin and outputs a JSON to stdout. The standard set of API functions (see [Wiki page](https://github.com/penrose/penrose/wiki/The-Penrose-API) for details). Example usage: `cat state.json | penrose runAPI > output.json`
* The renderer is refactored:
  * `Canvas` supports both interactive and static modes
  * Shapes are not by default `draggable` and inherit`IGPIProps` instead
  * DOM manipulation is minimized. Whenever needed, we used jsDOM instead of the actual DOM API
* Currently, we __do not support image imports__ and __estimate the dimensions of the labels via hand-written heuristics__ since `getBBox` is not available on the server side.

# Examples with steps to reproduce them

* `npm start -- set-theory-domain/tree.sub set-theory-domain/venn.sty set-theory-domain/setTheory.dsl --outFile=output.svg`.
image
* `npm start -- set-theory-domain/tree.sub set-theory-domain/venn.sty set-theory-domain/setTheory.dsl --folders --outFile=output` produces the same diagram, but with extra files of metadata about the diagram. In this case, `output/` folder contains:
```
domain.dsl    meta.json     output.svg    style.sty     substance.sub
```

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [x] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

* Compiling the automator to a binary
* Timing the runtime of individual stages in the automator

### CODE REVIEW

**Comment by hypotext** [comment]
Thanks for your hard work on this @wodeni! Let me know if you want me to test any of the repro. Minor comments:

The preview image in the PR doesn't seem to match the real analysis command paths.

> Currently, we do not support image imports and estimate the dimensions of the labels via hand-written heuristics since getBBox is not available on the server side.

Are we planning to support image imports in the future? Seems important for having a full-featured batch-mode renderer.

**Comment by wodeni** [comment]
> Thanks for your hard work on this @wodeni! Let me know if you want me to test any of the repro. Minor comments:
> 
> * [x]  The preview image in the PR doesn't seem to match the real analysis command paths.
> 
> > Currently, we do not support image imports and estimate the dimensions of the labels via hand-written heuristics since getBBox is not available on the server side.
> 
> Are we planning to support image imports in the future? Seems important for having a full-featured batch-mode renderer.

My understanding is that we won't be doing performance tests using examples with image imports. The practical concern here is that we do a fair amount of browser-side hacking for images, so I decided to make it a TODO for now.

**Comment by keenancrane** [comment]
Yes, that’s wise: at this point we should think about how to change our examples to work around hard-to-implement features, rather than doing the hard implementation. (E.g., avoiding examples with image import if that takes extra time.)

@katherine: If you’re thinking about the teaser, screenshotting 5 or so random versions of it from the browser seems like a good solution for now.

**Comment by wodeni** [comment]
Merging this branch into `synthesizer` for now, as most of the work about server-side rendering is done.

**Pull request merged**
