### PR TITLE
feat: updated examples visible in gallery

### PR DESCRIPTION
**Pull request by rjainrjain**
# Description

We introduce updated diagram choices and layout for the gallery examples on the Penrose webpage, as well as ensuring a white background for each tile, irrespective of light/dark mode. 

# Implementation strategy and design decisions

With our choices, we intended to showcase (1) the diversity of the domains that Penrose can support, and (2) the complexity of specification of which Penrose is capable, to show potential users the extent of the power of the platform.

# Examples with steps to reproduce them

Here's a screenshot of the new gallery layout (with Jiří's diagrams!):

Screen Shot 2023-06-23 at 1 42 51 PM

Do let us know what to change!

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have reviewed any generated registry diagram changes

# Open questions

Wondering about cropping diagrams that usually have borders/planes to have them fill up their tiles — we've made such borders invisible but since they're pervasively referenced throughout the Style programs, we've left them in — meaning they can't get cropped correctly.

Always the potential for more diagrams to add and more tweaks to make to the layout!

### CODE REVIEW

**Comment by jiriminarcik** [comment]
Nice! I would also add random sampling example (https://github.com/penrose/penrose/pull/1404). From my examples, I also suggest `curve-examples/blobs`  (https://github.com/penrose/penrose/commit/1a59b0d8d4f48762a73e81cbc41a7d388f0985a8) or some of the Spectral graphs as this just got merged (https://github.com/penrose/penrose/pull/1487).

**Comment by keenancrane** [comment]
I did a few small updates/additions, and removed a couple diagrams from the registry that aren't quite ready for release.  We can always improve, but looking pretty good!  Ship it.

**Review by keenancrane — COMMENTED** [review]
👍

**Review by keenancrane — APPROVED** [review]
I'm not great at Git.  Approved.

**Pull request merged**
