### PR TITLE
[ready to merge] Centralize setTheory.dsl to one location

### PR DESCRIPTION
**Pull request by maxkrieger**
Got rid of the duplicate `setTheory.dsl` in `dsll/`.

### CODE REVIEW

**Comment by hypotext** [comment]
Can you confirm that some of the existing wiki set theory examples work with this change? I would build on this branch but it's gonna unregister a lot of my packages.

**Comment by maxkrieger** [comment]
Ah forgot about the wiki. Testing and making edits now.

**Comment by maxkrieger** [comment]
Updated the wiki and those commands work on my machine.

**Comment by hypotext** [comment]
SGTM, thanks

**Pull request merged**
