### PR TITLE
Element revisions for TOG paper

### PR DESCRIPTION
**Pull request by dormaayan**
**Not fully done yet, not ready to merge!**
# Description

Related issues: #192 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

### CODE REVIEW

**Comment by dormaayan** [comment]
Hey @hypotext!

I made all the revisions and I think it should be ready to merge, the LA `Element` program looks now:

```
------------------- Type Constructors --------------------

type Scalar : type
type VectorSpace : type
type Vector : type
type LinearMap : type

-------------------- Operators -----------------------

function neg: Vector v -> Vector
function scale: Scalar c * Vector v -> Vector cv
function addV: Vector * Vector -> Vector
function addS: Scalar s1 * Scalar s2 -> Scalar
function norm: Vector v -> Scalar
function innerProduct: Vector * Vector -> Scalar
function determinant: Vector * Vector -> Scalar
function apply: LinearMap f * Vector -> Vector

-------------------- Predicates -----------------------

predicate In: Vector * VectorSpace V
predicate From: LinearMap V * VectorSpace domain * VectorSpace codomain
predicate Not: Prop p1

--------------- Syntactic Sugar Definition -----------------

notation "det(v1, v2)" ~ "determinant(v1 , v2)"
notation "LinearMap f : U → V" ~ "LinearMap f;From(f,U,V)"
notation "v1 + v2" ~ "addV(v1,v2)"
notation "-v1" ~ "neg(v1)"
notation "Vector a ∈ U" ~ "Vector a;In(a,U)"
notation "|y1|" ~ "norm(y1)"
notation "<v1,v2>" ~ "innerProduct(v1 , v2)"
notation "s * v1" ~ "scale(s , v1)"
notation "Scalar c := " ~ "Scalar c ;c := "
notation "f(v)" ~ "apply(f,v)"
```

- There are optional var params now (except of `constructor`s where it is not optional)
- At one point we should make a global renaming for the entire system of `Dsll -> Element` but it's probably not the right time to create potential conflicts and weird things with others


Let me know when I can merge

**Comment by hypotext** [comment]
Awesome thanks @dormaayan! I'll review it today by porting the RA Element program. Maybe @wodeni can take a quick look at the parser revisions.

**Comment by dormaayan** [comment]
@hypotext , I already ported the RA Element program and it works the same

**Comment by hypotext** [comment]
Thanks, I just ported the set theory and mesh Element programs. Looks great. One small thing: for statements like `type Scalar : type`, can you remove the `: type` part?

**Comment by dormaayan** [comment]
@hypotext Done, I think we can merge

**Comment by hypotext** [comment]
Looks great, thanks again @dormaayan!

**Pull request merged**
