### PR TITLE
3D Venn style for sets

### PR DESCRIPTION
**Pull request by wodeni**
# Description

Related issues: #269 #60 

Using the strategy described in #269, created a "3D" style for Venn diagrams for sets.

# Implementation strategy and design decisions

* Fixed some bugs in the backend and frontend for pending properties: the backend finds pending paths _after_ `initShape`, because that's the function that populate all the `Pending` expressions in the translation. The frontend now only updates label dimensions when they are not set explicitly in Style. 
* Label dimensions are now changeable by setting `width` and `height` of the `<svg>` element.

# Examples with steps to reproduce them

`penrose set-theory-domain/tree.sub set-theory-domain/venn-3d.sty set-theory-domain/setTheory.dsl`
* Without variable label sizes:
3d-sets
image (1)

* With variable label sizes:
3d-sets-2
image

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

### CODE REVIEW

**Comment by wodeni** [comment]
Added the example to the IDE and tested other existing examples. Ready to merge

**Comment by hypotext** [comment]
Was able to repro and the code generally looks good. Thanks!

> the backend finds pending paths after initShape, because that's the function that populate all the Pending expressions in the translation.

That definitely seems like a bug. I'm surprised that it didn't cause problems earlier.

Notes
* The examples take a little longer to optimize than with the "flat" style. Wondering if it's due to the label sizes change.
* Also takes unusually long to resample.

**Comment by wodeni** [comment]
Make sure you have your opt-flag on (i.e. no `--fast`). The label dimensions might be the cause. The resample time should be the same. If it's still longer with the same binary, we can look into that.

**Comment by hypotext** [comment]
Yeah, I just rebuilt on master with `stack install --profile` and it still optimizes and samples slower than the "larger venn" example in the IDE. Maybe it's the profile flag? Does it feel a little slower on your machine too?

**Pull request merged**
