### PR TITLE
feat: Add examples with nonconvex shapes

### PR DESCRIPTION
**Pull request by jiriminarcik**
# Description

Followup to #877.

Added new examples with non-convex shapes and fixed some issues with the convex partitioning algorithm by switching to library `poly-partition` (see comments below).

# Examples with steps to reproduce them

- Triangle maze example:

Run `npx roger watch maze.sub maze.sty maze.dsl` in folder `examples/minkowski-tests/maze`.

Screenshot 2022-02-21 at 1 12 53

- Yin-Yang example:

Run `npx roger watch yin-yang.sub yin-yang.sty yin-yang.dsl` in folder `examples/minkowski-tests/yin-yang`.

image

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new ESLint warnings
- [x] I have reviewed any generated changes to the `diagrams/` folder

# Open questions

The optimiser struggles with the Yin-Yang example and often get stuck at an undesirable local minimum.

Screenshot 2022-02-28 at 20 55 36

### CODE REVIEW

**Comment by samestep** [comment]
The poly-decomp.js library (linked from #877) links to this page describing an algorithm, which explains the circumstances under which it inserts these Steiner points: https://mpen.ca/406/bayazit

**Comment by samestep** [comment]
I opened https://github.com/x6ud/poly-partition-js/pull/1 which would allow make `convexPartitions` work for polygons of arbitrary orientation:
```diff
diff --git a/packages/core/src/contrib/Minkowski.ts b/packages/core/src/contrib/Minkowski.ts
index d774e67f0..cd235e3a4 100644
--- a/packages/core/src/contrib/Minkowski.ts
+++ b/packages/core/src/contrib/Minkowski.ts
@@ -161,6 +161,9 @@ export const convexPartitions = (p: VarAD[][]): VarAD[][][] => {
   );
 
   const contour = [...pointMap.keys()];
+  if (isClockwise(contour)) {
+    contour.reverse();
+  }
   const convexPolygons = convexPartition(contour);
 
   return convexPolygons.map((poly) =>
```

**Review by samestep — APPROVED** [review]
Looks great, thanks @jiriminarcik! Do you want to add any of these to the registry?

**Comment by jiriminarcik** [comment]
> Looks great, thanks @jiriminarcik! Do you want to add any of these to the registry?

I added the maze example.

**Pull request merged**
