### PR TITLE
feat: improve registry schema and loading

### PR DESCRIPTION
**Pull request by maxkrieger**
# Description

This PR improves the registry format and refactors `@penrose/examples`. 

The current registry has both test and gallery examples. This PR make the registry a dual-purpose repository for test examples and diagram gallery in `editor` by differentiating them via the `gallery` key.

Currently, trios are bundled together and loaded as a single JSON file. The size of these files may potentially cause long load time as the registry grow. This PR resolves this by converting individual files to JSON objects, and thereby reducing load time in clients.

# Implementation

* Add `gallery` key to trios
* Show trios with `gallery` key set to `true` in example gallery of IDE. Do not show the trio otherwise.
* Reduce dependency on prebuilt trio files in demos, tests
* Add human-readable names to trios
* Remove human-readable names from style, domain, and substance in `registry.json`
* Use trio human-readable names in the IDE. 
* Updated the registry section of [`CONTRIBUTING.md`] to reflect the changes above

Todo: 
- [x] fix examples in synthesizer ui
- [x] display thumbnails as built in CI

### CODE REVIEW

**Comment by joshsunshine** [comment]
I updated the description to include changes to human-readable names.

**Comment by joshsunshine** [comment]
@samestep are there any instructions related to the registry besides what is in `CONTRIBUTING.md`?

**Comment by samestep** [comment]
> @samestep are there any instructions related to the registry besides what is in `CONTRIBUTING.md`?

Nothing comes to mind.

**Comment by joshsunshine** [comment]
@wodeni What do you mean by "and loading" in this PR title?

**Comment by joshsunshine** [comment]
@wodeni If the `gallery` key is not set is the trio shown in the gallery? In other words, is the default value of the `gallery` key `true` or `false`?

**Comment by wodeni** [comment]
> @wodeni What do you mean by "and loading" in this PR title?

Updated the PR description to explain this.

> @wodeni If the `gallery` key is not set is the trio shown in the gallery? In other words, is the default value of the `gallery` key `true` or `false`?

The default is `undefined`.

**Comment by joshsunshine** [comment]
> The default is `undefined`.

What is the behavior when `gallery` is `undefined`?

**Comment by maxkrieger** [comment]
@joshsunshine its equivalent to being false, ie a falsy value

**Comment by wodeni** [comment]
image

Here is readable names + previews. I'll leave to code in commented out in `ExamplesBrowser` as the diagrams aren't cropped for display yet. I think this is out of scope for the current PR and another PR should address this issue for production use.

**Review by joshsunshine — CHANGES_REQUESTED** [review]
What I see looks good, but please: 

- Edit CONTRIBUTING.md to reflect the changes to registry.json.
- Remove the names from style, substance, and domain.
- Add the caffeine and one of the walk-on-spheres examples to the gallery.

**Review by joshsunshine — CHANGES_REQUESTED** [review]
Please:
- Explain the `gallery` key and give an example of its uses in `CONTRIBUTING.md`.
- Fix the build

**Review by joshsunshine — APPROVED** [review]

**Pull request merged**
