### PR TITLE
feat: Expose random sampling in Style

### PR DESCRIPTION
**Pull request by keenancrane**
# Description

image

This PR exposes generic random sampling in Style, adding several sampling functions to the function library that commonly arise in diagrams.  The ability to set values to random constants is especially helpful for simplifying programs that would otherwise need to enforce containment in a set via constraints.  The point here is not to reduce problem size, but rather to reduce "fighting" between constraints/objectives, and in turn minimize the amount of problem-tweaking needed to make a good-looking diagram.

A new example in `examples/src/random-sampling` provides tests for the sampling method.  This example looks nice and steers users toward potentially useful functionality, so it is also now included in the gallery.  `CONTRIBUTING.md` has also been updated to explain that tests should be added to the set of examples (as done here).

The PR also adds a `Random Sampling` item to the (Vite) Style documentation, explaining that randomly-sampled values depend on the `variation`, and otherwise basically behave like constants (e.g., they cannot be optimized or changed, just like any other numerical constant).  Hopefully this helps avoid common misunderstandings of how sampling works / what it means.

# Implementation strategy and design decisions

The PR introduces the following functions:

- `random( minVal, maxVal )` — samples a random constant uniformly from the range `[minVal,maxVal]`
- `unitRandom()` — samples a random constant uniformly from the range `[0,1]`.
- `normalRandom()` — samples a random constant from a normal distribution with mean 0 and standard deviation 1.
- `diskRandom()` — samples a random point uniformly from the unit disk.
- `sphereRandom()` — samples a random point uniformly from the unit sphere.
- `triangleRandom(a,b,c)` — samples a random point uniformly from a triangle with vertices `a`, `b`, `c`.

# Checklist

- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have reviewed any generated registry diagram changes

# Open questions

There may be other common samplers not implemented here, but seems fine to add them in a future PR.

Another very reasonable thing to do in the future is to create samplers associated with shapes, i.e., provide a method like `uniformSample( S )` where `S` has any of our shape types (`Circle`, `Rectangle`, `Ellipse`, `Polygon`, etc.).  This then becomes one of our basic geometric queries, similar to (signed) distances and closest points.

### CODE REVIEW

**Review by samestep — CHANGES_REQUESTED** [review]
Looks great, thanks for implementing and documenting these! Could you add some tests for them so they don't break in the future? I see that you have a teaser diagram in your PR description; if that was generated via Penrose then you could just add that trio to the registry.

**Comment by samestep** [comment]
Also, could you be more precise about inclusive/exclusive ranges in your documentation? The `uniform` sampler is inclusive of the lower bound and exclusive of the upper bound; it would be good to be accurate about that in your `random` and `unitRandom` function documentation, for instance.

**Comment by keenancrane** [comment]
> The `uniform` sampler is inclusive of the lower bound and exclusive of the upper bound; it would be good to be accurate about that in your `random` and `unitRandom` function documentation, for instance.

I guess you're referring to [this line](https://github.com/davidbau/seedrandom/blob/released/seedrandom.js#LL72C1-L72C1)?

> Also, could you be more precise about inclusive/exclusive ranges in your documentation?

I hesitate to say this in the docs, because it may lead diagrammers to worry about things they shouldn't (e.g., _"ok, so then how do I get values in [0,1] rather than [0,1)_? Now I'm worried!").

In the continuous setting, there is no difference between saying "draw a sample uniformly at random from [0,1]" and "draw a sample uniformly at random from "[0,1]" (unless you really want to split hairs and consider [nonstandard assumptions](https://stats.stackexchange.com/questions/140805/in-the-definition-of-probability-density-function-does-it-matter-if-the-interva)).

In the implementation, there is indeed a formal difference in the sense that (due to the line cited above) the value 1.0 will never be sampled by the PRNG.  But also note the comment

```
// This function returns a random double in [0, 1) that contains
// randomness in every bit of the mantissa of the IEEE 754 value.
```

Such a value has 24 bits of mantissa, meaning that the interval of the real line closer to the value `1.0` than any other floating-point value has size (approximately...) 1/2^24 ≈ 0.000000059604645.  Especially in the diagramming context, this is not something that is going to have any discernible impact.  (Even for more demanding applications like numerical integration and cryptography, it would be quite hard to detect.)

**Review by wodeni — CHANGES_REQUESTED** [review]
Looks good! Thanks for the detailed docs and PR description. I think this PR fixes https://github.com/penrose/penrose/issues/1020?

Like @samestep said, it'd be great to add the trios in the teaser figure in the registry as well!

**Comment by keenancrane** [comment]
Thanks for the feedback, @samestep and @wodeni!

I've also now added an example, and updated the registry accordingly.

Let me know if you spot anything else…

**Review by samestep — APPROVED** [review]

**Review by wodeni — APPROVED** [review]
Thanks for the examples! They look great

**Review by wodeni — APPROVED** [review]
Thanks for the examples! They look great

**Pull request merged**
