### PR TITLE
Implement real analysis domain [with IDE]

### PR DESCRIPTION
**Pull request by hypotext**
# TODOs

Last updated 11/26/18 by Katherine.

- [x] **Get compiler output back**
- [x] Shapes
  - [x] Paths: React component (Nimo/Max)
    - [x] Render, drag, step, autostep, resample, opt output. ETA: 1 week (11/13)
    - [x]  **Fix bug: need to draw lines using the L command (currently it's just moving to a bunch of points without drawing the lines)**
  - [x] Make shapes using paths
    - [x] Curves
    - [x] **Improve integral shape** (KY)
    - [x] **Shapes for continuous/discontinuous functions (if needed)** (KY)
    - [x] **Improve derivative shape**
    - [x] Parens
    - [x] Braces
    - [x] Beautiful arrow (path with arrowheads)
- [ ] Opt
  - [ ] **Improve labeling**
  - [x] **Make the layout work "better/faster"**
  - [x] **Better randomization/sampling** #161 
  - [ ] Add any other new objective functions needed
  - [ ] Optimizing on paths (e.g. their bboxes or control points)
- [ ] Language features
  - [x] Match with respect to subtyping
    - [ ] Kinds of intervals #163 
    - [ ] Kinds of functions
  - [ ] Match value constructors
  - [ ] "Could equal" matching by type: `Set A, B; A ?= B`
  - [ ] Copy semantics for GPIs
  - [ ] String manipulation functions in Style
  - [x] Layering (coord with frontend)
  - [ ] _Maybe: programmatic # GPIs_
    - [ ] _design, lists, indexing_
  - [ ] _Maybe: matching anonymous expressions_
- [x] Book and Substance (Dor)
  - [x] Syntactic sugar in book and for Style programs (Dor)
  - [x] Prelude exports (Dor)
  - [x] Value deconstructors in Substance (Dor)
  - [ ] Document these language features in the design paper (Dor)
- [ ] Style programs
  - [x] Add continuous function and discontinuous function styles
  - [ ] Use value deconstructors
  - [ ] Variety of smaller and larger (compositional) Substance programs
  - [ ] Variety of smaller and larger (compositional) Style programs
  - [x] Perpendicular style
  - [x] Parallel style
  - [ ] Have the two Styles working with the same Sub program
- [ ] Element programs
  - [ ] Use Prelude
- [ ] Substance programs
  - [ ] Use syntactic sugar
  - [ ] Use Prelude
- [ ] Documentation
  - [ ] Keep writing [experience notes](https://github.com/penrose/penrose/wiki/Working-notes-on-implementing-the-real-analysis-domain)
  - [ ] Document how each Style works
  - [ ] Document the new language features
  - [ ] Document PR
- [ ] Learn React (Katherine)

Example code for braces

```
Shapes {
       Shapes.brace = Path {
       		    	    file = "brace.svg"
		    }		    
}

Interval A {
	 -- Style compiler "copies" right side, checks the right side has no references outside of the block
	 A.left = COPY(Shapes.brace)
	 A.right = COPY(Shapes.brace)
	 override A.left.color = red

	-- Only A.left is red
	-- Possible copy syntax: A.left <= Shapes.brace
}
```

# Plan

- [x] Max and Nimo implement frontend, including paths
- [ ] Katherine implements RA language features using old frontend
- [ ] When paths work in new frontend, Katherine migrates work and starts to improve graphical aspects of RA domain

---

# Description

Implement the real analysis domain, as described in the design paper.

Related issues: #90 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

### CODE REVIEW

**Comment by hypotext** [comment]
Forking from #131 (implement real analysis domain) but with IDE.

**Comment by wodeni** [comment]
I pushed a couple of things:

- The curve renderer should be better now:
image
- I enforced type checking for computations and thus had to populate `compSignatures`, which was missing from prior commits. Now you will get meaningful error messages if you invoke comp functions with wrong arguments!
- I brought error messages back to our new frontend:
  - a couple of `IO` functions are created to simplify the main function
  - For now, all Style compiler output is printed into stdout, which is not scalable in multi-server scenarios. I will leave it as it is for now, but in a future release, somewhere like `[DEBUG]` level of the logger would be a better place to go.

**Comment by wodeni** [comment]
We finally got rid of those hardcoded ugly arrowheads! Presenting a bunch of pretty arrowheads with arcs:
image

**Comment by wodeni** [comment]
## Current status of the perpendicular style

* Three test cases:
  * `penrose real-analysis-domain/continuous_fn.sub real-analysis-domain/real-analysis.sty real-analysis-domain/real-analysis.dsl`
image
  * `penrose real-analysis-domain/discontinuous_fn.sub real-analysis-domain/real-analysis.sty real-analysis-domain/real-analysis.dsl`
image
  * `penrose real-analysis-domain/point-perp.sub real-analysis-domain/real-analysis.sty real-analysis-domain/real-analysis.dsl` 
     * No preview yet since optimization takes very long
* Pending issues:
  * Sampling curves: more options should be available for curve sampling
  * A hack in `evalFnArgs`: I did not choose to pass in the newest `rng` to save time. If there is a case where arguments to an obj/constr are computations with randomization, we need to change this.
  * A bug in `disjoint(Line, Line)`: this objective allows cases where intervals overlap, e.g.:
bug

**Comment by hypotext** [comment]
After letting `point-perp.sub` run for maybe 10 minutes: (note it takes 8s per step)

image

**Comment by wodeni** [comment]
## Importing external images in Style

- Example: `penrose real-analysis-domain/interval-types.sub real-analysis-domain/real-analysis-types.sty real-analysis-domain/real-analysis.dsl`
- `Image` shape type supports image import. 
- `path` property includes the path to the image. 
    - Regardless of whether you are running `react-renderer` or `ide-frontend`, images to be imported must be placed into `TOP/src/[react-renderer|ide-frontend]`/public`. This is due to cross origin limitations  
- Both `lengthX` and `lengthY` need to be specified, or the default value will be randomly selected. The render do respect aspect-ratio for now. The determination of the image size follows the SVG standard here:
    - I did not spend much time digging into the standard, so I used the default value of `preserveAspectRatio`
- Only SVG images are tested. Theoretically PNG and JPEG are also supported
- The server does support dragging of `Image`s, but this functionality is not thoroughly tested yet, especially its interaction with drag update functions in the `Server` module

**Comment by hypotext** [comment]
`real-analysis-domain/interval-par.sub real-analysis-domain/parallel-reals2.sty real-analysis-domain/real-analysis.dsl`

image
image
image

TODO: only looks good with intervals with certain relative sizes/locations. 

Also, can only adjust the interval sizes and positions (to re-optimize) by dragging their labels. Should come up with a better direct manipulation method.

**Comment by maxkrieger** [comment]
Before merging with master, do you want me to clean up some extraneous files from my docker exploration that won't be used (`Dockerfile.base`, `Makefile`, `stack-native.yaml`) since they might be misleading?
Should we also deprecate the old `front-end/` more clearly?

**Comment by hypotext** [comment]
> do you want me to clean up some extraneous files

Sure, thanks!

> Should we also deprecate the old front-end/ more clearly?

Yes, let's figure out how to do that when it's time to merge.

**Comment by maxkrieger** [comment]
Will do the cleanup.

Another task before merging:

* [ ] applying some of the patches in `end-user-frontend-edits` to this branch - we have to cherrypick just the ones in the frontend/ide because there are also some intermediate edits to the haskell files that probably shouldn't override what you have here.

**Comment by hypotext** [comment]
More documentation after performance tuning:
`function-composition.sub` works pretty well after I improved the curve calculations. (This took 10 seconds.)

image

**Comment by wodeni** [comment]
Merged manually in c99510abc6311e8a822031f6e42dcd86a8057c54. Closing the PR now.

**Pull request closed without merging**
