### PR TITLE
Make example diagrams for the paper (linear algebra)

### PR DESCRIPTION
**Pull request by hypotext**
`runpenrose linear-algebra-domain/twoVectorsPerp.sub linear-algebra-domain/linear-algebra-paper.sty linear-algebra-domain/linear-algebra.dsl`

Paper:

image

Current:

image

image

See issues in the [paper repo issues](https://github.com/penrose/TOG-2019/issues)

----

[comp graph files](https://github.com/penrose/penrose/tree/paper-example/src/comp-graph-domain)

`runpenrose2 comp-graph-domain/paper-example-graph.sub comp-graph-domain/comp-graph.sty comp-graph-domain/comp-graph.dsl`

image

----

# Description

Related issues: # (issue)

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

* Investigate possible slowness of polymorphic map lookup https://github.com/penrose/penrose/issues/257
* Improve label position WRT arrowhead (@wodeni has a direction for fixing this??)

### CODE REVIEW

**Comment by hypotext** [comment]
Hey @wodeni I pulled master on this branch so I can get the new arrows, and when I recompile the system and run it with the new frontend with different examples, I'm getting an `Error reading JSON` output (presumably the frontend is sending back something in a different format). The initial state of the diagram renders, but optimization doesn't work. No console logs in frontend.

I made sure to run the new Penrose binary with a newly recompiled frontend, so I'm not sure why they are incompatible now. I also don't think this branch made any changes that would result in a JSON error.

Any idea why this is happening?

Command:

```
/Users/katherineye/Desktop/Code/penrose/.stack-work/install/x86_64-osx/lts-13.24/8.6.5/bin/penrose examples/linear-algebra-domain/determinants.sub examples/linear-algebra-domain/linear-algebra.sty examples/linear-algebra-domain/linear-algebra.dsl
```

Output:

```
(...)
Opt config:

OptConfig {optMethod = LBFGS}
Penrose renderer server started on ws://127.0.0.1:9160/
Waiting for the frontend UI to connect...
Error reading JSON
Error reading JSON
```

**Comment by hypotext** [comment]
Basically, could you or @maxkrieger check out this branch and see if it works on your machine? Thanks!

**Comment by wodeni** [comment]
It's the `getVersion` call that's failing. Looking into it now.

**Comment by wodeni** [comment]
> Basically, could you or @maxkrieger check out this branch and see if it works on your machine? Thanks!

Should be resolved by the recent commits. It was caused by a feature implemented in the backend but not the frontend.

**Pull request merged**
