### PR TITLE
fix: Add Support for images with absolute URLs

### PR DESCRIPTION
**Pull request by cmumatt**
# Description

Fixes issue #1032

This PR provides support for absolute image URLs in Style programs within the IDE and Automator.  When a URL is absolute, it is fetched directly and thus bypasses the normal example/roger/local/gist handlers.

# Implementation strategy and design decisions

Detect and handle absolute image URLs.  Only handle relative URLs using the existing logic in the IDE and Automator.

# Checklist

- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new ESLint warnings
- [X] I have reviewed any generated changes to the `diagrams/` folder

# Open questions

- Local image fetching in the IDE is currently marked as TODO.  See issue #1035.  This needs to be implemented in a separate PR.
- Absolute image resolution in the IDE does not use a proxy to bypass CORS.  If the web server hosting the image does not provide headers indicating a cross-origin request is allowed (e.g., `Access-Control-Allow-Origin: *`) then the browser will not fulfill the request and the placeholder image will be displayed instead.

### CODE REVIEW

**Comment by joshsunshine** [comment]
@cmumatt Please add a test to the registry that includes Image shapes with `href` properties corresponding to various absolute URLs.

**Comment by joshsunshine** [comment]
This doesn't seem to work yet with `https://www.cs.cmu.edu/~jssunshi/images/ball.svg`

**Comment by cmumatt** [comment]
> @cmumatt Please add a test to the registry that includes Image shapes with `href` properties corresponding to various absolute URLs.

Thanks!  Replace relative paths with absolute URLs in: `packages/examples/src/set-theory-domain/venn-3d.sty`

**Comment by cmumatt** [comment]
> This doesn't seem to work yet with `https://www.cs.cmu.edu/~jssunshi/images/ball.svg`

This is CORS.  If the web server allowed the cross-origin request or we implemented a CORS proxy, then the image would fetch successfully.  I've created a separate issue (#1036) to track CORS concerns.

**Pull request merged**
