### PR TITLE
Finish real analysis domain

### PR DESCRIPTION
**Pull request by hypotext**
Finishing up loose ends from #90 and #143.

Related issues: [#90](https://github.com/penrose/penrose/issues/90)

# Examples with steps to reproduce them

`runpenrose real-analysis-domain/spec-RA.sub real-analysis-domain/perpendicular-RA.sty real-analysis-domain/real-analysis.dsl`

image

`runpenrose real-analysis-domain/spec-RA.sub real-analysis-domain/parallel-RA.sty real-analysis-domain/real-analysis.dsl`

image

# TODO

- [x] Finish fast diagram resampling and document it
- [x] Finish parallel reals style
- [x] Merge Substance specs
- [ ] Element programs use Prelude (Dor)
- [ ] Substance programs (Dor)
  - [ ] Use syntactic sugar
  - [ ] Use Prelude
- [ ] Documentation (Katherine)
  - [ ] Write [experience notes](https://github.com/penrose/penrose/wiki/Working-notes-on-implementing-the-real-analysis-domain)
  - [ ] Document how each Style works

# Checklist

- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

- [ ] Write Substance programs that test each Style more thoroughly, e.g. with random program generator
- [ ] Why does resampling the initial state generate wrong shapes / labels, but resampling subsequent states after the wrong one generate the correct GPIs?
- [ ] Add function composition to the spec Substance program to more fully showcase the second Style

### CODE REVIEW

**Comment by hypotext** [comment]
Some of the successful examples from the newest commit: `runpenrose real-analysis-domain/spec-RA-2.sub real-analysis-domain/parallel-RA.sty real-analysis-domain/real-analysis.dsl`

image
image
image

Some of the labeling and objectives are special-cased for this example, though.

@wodeni Do you know how we can make the arrowhead size specifiable in Style? The green arrowhead is too big but I want to preserve the thickness of the arrow body.

**Comment by hypotext** [comment]
Hey @dormaayan, I think the real analysis domain is ready for testing + enhancement. The two styles in the PR README (`perpendicular-RA.sub` and `parallel-RA.sty`) both work on the same Substance program `spec-RA.sub`. 

Would you be able to test the Prelude + syntactic sugar with the Element and Substance program? Would also be great to use the program generator on this domain, but that's lower-priority.

**Comment by dormaayan** [comment]
@hypotext , now the new IDE works well with the syntactic sugars and the prelude 🎉 
You can find the sugared spec at `spec-RA-sugared.sub` and it works well with the two styles.

Note the syntactic sugar is extetndable you can add new notations any time to the .dsl file

I'm still having some issues with the random generator but hope to have something useable soon

Please let me know if anything is needed

**Comment by hypotext** [comment]
@dormaayan Awesome, thank you! I'll test everything end-to-end after we merge `end-user` to master (hopefully soon).

**Pull request merged**
