### PR TITLE
docs: Write a CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by samestep**
# Description

Per the discussion in https://github.com/penrose/penrose/pull/1081#issuecomment-1238535418, this PR takes the contents from the four "**For the contributor**" pages on our wiki, plus two other pages...

- [Building and running](https://github.com/penrose/penrose/wiki/Building-and-running)
- [Registry](https://github.com/penrose/penrose/wiki/Registry)
- [Contributor guide](https://github.com/penrose/penrose/wiki/Contributor-guide)
- [Setting up VSCode](https://github.com/penrose/penrose/wiki/Setting-up-VSCode)
- [Workflow for merging a branch](https://github.com/penrose/penrose/wiki/Workflow-for-merging-a-branch)
- [Troubleshooting](https://github.com/penrose/penrose/wiki/Troubleshooting)

... updates and reorganizes that content where necessary, and puts it into a [`CONTRIBUTING.md`](https://en.wikipedia.org/wiki/Contributing_guidelines) file in the repo itself. I propose that we merge this PR, then replace the contents of all those pages (along with the "Contributor guide" link on the wiki [Home](https://github.com/penrose/penrose/wiki) page) with just a link to the `CONTRIBUTING.md` file in the repo.

This PR includes in the `CONTRIBUTING.md` a table of contents autogenerated by [markdown-toc](https://www.npmjs.com/package/markdown-toc), and modifies our `readme` CI job to make sure that table of contents gets kept up to date.

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new ESLint warnings
- [x] I have reviewed any generated changes to the `diagrams/` folder

# Open questions

- The "[Getting started](https://github.com/penrose/penrose/wiki/Getting-started)" wiki page also has some relevant content for contributors. We should bring that content into `CONTRIBUTING.md` in a followup PR.
- Should the two commands from our `readme` CI job be added to what our `yarn format` script does? Then we could delete the `readme` CI job and just have the `format` CI job.

### CODE REVIEW

**Review by wodeni — APPROVED** [review]
Looks great. Thanks for consolidating and adding to the docs!

**Comment by joshsunshine** [comment]
@samestep please check that all links to these pages in the wiki now point to `CONTRIBUTING.md`? For example, the [Welcome page](https://penrose.cs.cmu.edu/docs/tutorial/welcome) of the tutorial currently links to the "Building and Running" page of the wiki.

**Comment by joshsunshine** [comment]
> The "[Getting started](https://github.com/penrose/penrose/wiki/Getting-started)" wiki page also has some relevant content for contributors. We should bring that content into CONTRIBUTING.md in a followup PR.

Why wait? Why not do this in this PR?

**Comment by samestep** [comment]
> Why wait? Why not do this in this PR?

It would take a lot more time for not a ton of immediate benefit, and I want to get this PR merged now to unblock #1081.

**Comment by joshsunshine** [comment]
> I propose that we merge this PR, then replace the contents of all those pages (along with the "Contributor guide" link on the wiki [Home](https://github.com/penrose/penrose/wiki) page) with just a link to the CONTRIBUTING.md file in the repo.

Why keep these six pages around? Is the idea just to preserve any links? I think that's a reasonable idea, but we should remove the pages from the wiki sidebar.

**Review by joshsunshine — APPROVED** [review]

**Comment by samestep** [comment]
> Why keep these six pages around? Is the idea just to preserve any links? I think that's a reasonable idea, but we should remove the pages from the wiki sidebar.

Yes, the idea is to just avoid breaking links unnecessarily. I agree that we should remove them from the sidebar.

**Pull request merged**
