### PR TITLE
Substance program synthesizer

### PR DESCRIPTION
**Pull request by wodeni**
__In progress. Not ready for merging__

# Description

Related issues: #107 #144 #103 

This PR contains a new version of a Substance program synthesizer, which is designed to:
* Generate random Substance programs from a Domain program
* Generate Substance programs given a set of rules such as "only generate predicates". 
* Generate new Substance programs given an existing Substance program as the starter, e.g.:
```
Set A, B, C
```
One of the many generated programs can be:
```
Set A, B, C
IsSubset(A, B)
IsSubset(B, C)
```
To this end, this new system is a bit more than a "generator" but rather a "synthesizer", which produces valid programs given a higher-level specification, hence the name of the module. 

# Implementation strategy and design decisions

* Complete rewrite of the generator in #103:
  * Encapsulate the synthesis context into a `State` monad (read "Tasteful stateful computations" in [LYHGG](http://learnyouahaskell.com/for-a-few-monads-more) for more motivation). This is a common practice for any stateful Haskell programs, e.g. parsers.
  * Add a Substance pretty printer in `Penrose.Pretty`: the previous version concatenate strings instead of composing a Substance AST, which does not scale well and has no correctness guarantee. As an essential step to improve this, `prettySubstance` outputs a well-formed Substance program given its AST;
  * Compose generated statements at an AST level: all synthesizer functions now accumulate a Substance AST instead of a big string. One potential benefit is that we could do program transformations on the output if needed.
* Integration with the Penrose API:
  * Whenever `penrose-synthesizer` is supplied with a Style program, it attempts to compile each of the generated Substance with the supplied Domain and Style programs. A single function call to the API (`compileTrio`) does this rather effortlessly.
  * In addition, all other API functions can be used in the synthesis module. For instance, one could call `stepUntilConvergence` after compilation and get a final `State`, which can be either rendered (see below for more discussion) or written to the file system as a JSON file.

# Evaluation

* Performance metrics: _not implemented_
  * Compilation time: parsing cost for each program in the trio, growth of compilation time vs. the number of selector matches vs. the length of substance.
  * Optimization metrics: (__not a TOG item__) steps/time to convergence, energy change over time
* Style coverage: (__not a TOG item__) with a sufficient number of sample Substance programs, one can test the "coverage" of a given Style program by checking the number of selector matches/constraints/shapes over the set of samples. If one wants to write a "generic" Style program that is supposed to work with the whole space of Substance programs, this can be a good indicator of the coverage.
* Inferring dependencies in Substance introduced by Style:  (__not a TOG item__) Style introduces certain "constraints" on the kinds of valid Substance programs. For instance, you cannot have cyclic `IsSubset` relations in Substance. This "constraint" manifest as a runtime error in the system: layering computation fails because of the cyclic graph. More commonly, these "constraints" surface as non-satisfiable sets of constraints. By easily generating a sufficiently large number of Substance programs (modulo other system support for reporting violated constraints), one could report to the user about these hidden "constraints" introduced by Style.  

# Examples with steps to reproduce them

Usage of the synthesizer:
```
Usage:
  penrose-synthesizer <domain> [options]

Options:
  --substance=SUB      A Substance program that will be included in every synthesized program
  --style=STY          A Style program that the synthesized programs work with
  --num-programs=NUM   The number of programs to generate
                       [default: 1]
  --path=PATH          Output path for the generated programs (Trailing slash not needed)
                       [default: synthesized-progs]
  --min-length=MINLEN  Minimum number of statements in each generated program
                       [default: 1]
  --max-length=MAXLEN  Maximum number of statements in each generated program
                       [default: 10]
  --declaration        A flag telling the synthesizer to generate new declarations
  --predicate          A flag telling the synthesizer to generate new predicates
  --binding            A flag telling the synthesizer to generate new bindings
  --arg-mode=MODE      Argument generation mode: (1) generated: always generate new type declarations; (2) existing: attempt to search for constructs that apply to existing statements and switch to (1) after exhaustive search; (3) 50% chance of (1) or (2)
                       [default: mixed]
```
To build the binary, run `stack install`, which builds both `penrose` and `penrose-synthesizer`.
To run the synthesizer, navigate to `TOP/penrose-synthesizer` and try:
`penrose-synthesizer --num-programs=1000 --max-length=20 --style=../examples/set-theory-domain/venn.sty ../examples/set-theory-domain/setTheory.dsl`

This command generates 1000 Substance programs ranging from 1 to 20 lines and compile them with `setTheory.dsl` and `venn.sty`.

# Open questions

* Other than the length distribution of generated programs, what else do we want to control? Some candidates:
  * Reuse of variables: the system as 3 modes `Generate` (always generate new variables when declaring a new predicate or function), `Existing` (attempts to reuse existing variables first, if none exist, generate new ones), and `Mixed` (50/50 of the former two approaches).
  * Types of statements allowed: a subset of value constructors, predicates, operators, variable declarations...
  * Distribution of the types of statements: e.g.  80% declaration, 20% predicates
  * Nestedness: min/max level of nestedness in functions and predicates
  * Variable naming convention: currently, it's `<prefix-of-typename>+<int>`
* If we use the synthesizer to enumerate all possible programs in a limited space (say, all `IsSubset` predicates for `Set A, B, C`), there should be a stopping condition for the generation. How do we know that we have generated all the possible programs? For Substance, this seems to require some processing and transformation of the ASTs to determine program equivalence.
* Rendering the output:
  * Currently, the frontend is written in the browser and we would like to run the renderer headless. There are several problems ahead:
    * Generating the SVGs headless: we use the DOM API to manipulate SVG attributes before rendering them. This could be done via server-side rendering (SSR) support by react [`ReactDOMServer`](https://reactjs.org/docs/react-dom-server.html).
    * Headless MathJax: we use the client version of MathJax to generate label paths and collect label dimensions. There is a [node version of MathJax](https://github.com/mathjax/MathJax-node), but more testing needs to be done to determine if it's reliable for SVG generation.
    * A proposed pipeline: 
        * MathJax node: MathJax SVG string label
        * [JSDom](https://github.com/jsdom/jsdom) manipulations to make nice SVG string labels 
        * react-SSR parameterized by nice SVG strings to generate diagrams

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

### CODE REVIEW

**Comment by wodeni** [comment]
Update: the synthesizer can now take in a Substance program, generate a bunch of predicate _without_ declaring new objects, and compile the synthesized programs into initial `State`s.

Same example input:
```
Set A, B, C
```

Run the following command in `TOP/examples` (technically it can beany directory but note that it will create a folder called `synthesized-progs` by default):
```
penrose-synthesizer ../examples/set-theory-domain/setTheory.dsl  --style=set-theory-domain/venn.sty --substance=set-theory-domain/threesets.sub --num-programs=100 --max-length=10 --arg-mode=existing --predicate
```

You will get 100 programs that all start with the same Substance, and additional predicates on sets. Here are some examples:

```
AutoLabel All
Set A
Set B
Set C
Nonempty(B)
Intersect(A, A)
NotSubset(C, B)
Intersect(A, A)
Intersect(A, B)
IsSubset(A, B)
IsSubset(A, A)
IsSubset(A, C)
Nonempty(A)
NotIntersecting(B, A)
```

```
AutoLabel All
Set A
Set B
Set C
NotIntersecting(A, B)
```

```
AutoLabel All
Set A
Set B
Set C
Intersect(B, A)
Intersect(A, C)
IsSubset(C, C)
NotIntersecting(C, C)
NotSubset(B, C)
IsSubset(B, C)
Empty(B)
Empty(C)
```

See all generated programs [here](https://drive.google.com/drive/folders/1R6q3Ttih8sxq3hrfYNx9GJobDGOyoO15?usp=sharing) (Google Drive link. Didn't want to upload 4.8M of text files to pollute the repo).

**Comment by wodeni** [comment]
Okay, we can now parametrize the synthesizer by a smaller Domain program. For instance, let's only have `IsSubset()` in the spec-domain program, `spec.dsl`:
```
predicate IsSubset : Set s1 * Set s2
```
Using `spec.dsl` as an input to the synthesizer, we now generate 10 programs:
```
$ penrose-synthesizer ../examples/set-theory-domain/setTheory.dsl --substance=set-theory-domain/threesets.sub --spec=spec.dsl --num-programs=10 --max-length=10 --arg-mode=existing --predicate

Generated new program (synthesized-progs/prog-1.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(B, A)
IsSubset(A, A)
IsSubset(B, B)
IsSubset(A, B)
IsSubset(B, A)
IsSubset(B, C)
IsSubset(A, A)
IsSubset(C, C)
IsSubset(C, B)
IsSubset(A, B)
Generated new program (synthesized-progs/prog-2.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(B, B)
IsSubset(B, C)
IsSubset(C, C)
IsSubset(B, A)
IsSubset(B, A)
IsSubset(B, A)
IsSubset(A, C)
IsSubset(C, C)
IsSubset(B, C)
IsSubset(A, B)
Generated new program (synthesized-progs/prog-3.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(B, A)
IsSubset(C, B)
IsSubset(C, B)
IsSubset(C, B)
IsSubset(A, C)
IsSubset(B, A)
IsSubset(C, C)
Generated new program (synthesized-progs/prog-4.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(A, A)
IsSubset(B, B)
IsSubset(C, C)
IsSubset(C, B)
IsSubset(B, B)
IsSubset(C, A)
IsSubset(B, B)
IsSubset(A, B)
IsSubset(A, B)
IsSubset(A, A)
Generated new program (synthesized-progs/prog-5.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(A, A)
IsSubset(B, B)
IsSubset(B, C)
IsSubset(C, C)
Generated new program (synthesized-progs/prog-6.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(B, B)
IsSubset(A, B)
Generated new program (synthesized-progs/prog-7.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(B, C)
IsSubset(B, A)
IsSubset(A, B)
IsSubset(C, B)
Generated new program (synthesized-progs/prog-8.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(B, C)
IsSubset(B, C)
IsSubset(B, B)
IsSubset(B, C)
IsSubset(C, A)
IsSubset(B, B)
IsSubset(C, C)
IsSubset(A, A)
Generated new program (synthesized-progs/prog-9.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(C, C)
IsSubset(B, B)
IsSubset(A, C)
IsSubset(A, B)
IsSubset(A, A)
IsSubset(B, B)
IsSubset(C, C)
IsSubset(B, B)
Generated new program (synthesized-progs/prog-10.sub):
AutoLabel All
Set A
Set B
Set C
IsSubset(B, C)
IsSubset(B, C)
IsSubset(C, B)
IsSubset(A, A)
IsSubset(A, A)
IsSubset(C, C)
IsSubset(C, A)
IsSubset(B, B)
```

**Comment by wodeni** [comment]
# Penrose headless mode

This branch now contains changes to achieve headless rendering of Penrose diagrams. As a starter, here's a plan to implement it (with @maxkrieger):

- [x] CompileTrio
  * Input: (String, String, String)
  * Output: State JSON
  * `JSON string of [String, string, string] | penrose runAPI`
- [x] Label generation (JSDOM: MathJax Node)
  * Input: State JSON / a list of label props JSON
  * Output: [(SVG string (unstyled), w, h)]
- [x]  UpdateState: State -> State
- [x]  StepUntilConvergence: State -> State
  * `State JSON string | penrose runAPI`
- [ ] Label Styling:
  * Input: optimized State JSON / [SVG string (unstyled)]
  * Output: [JSDOM’ed SVG]
- [ ] Rendering (ReactSSR)
  * Input: optimized State JSON, [JSDOM’ed SVGs]
  * Output: an SVG file

**Comment by wodeni** [comment]
I did some experiments with React SSR, here are my current results.

* It's actually very easy to use, I used `ReactDOMServer.renderToString(<Canvas state={state}></Canvas>)`, which converts a React component to a string. 
* The current `Canvas` component has many extraneous props that are _not_ optional, e.g. layer. I wrote another component `StaticCanvas`, which is a subset of the current one. 
* The biggest problem I had is the mixed interfaces for `IGPIProps` and `IGPIPropsDraggable`. I changed the interfaces to make it work:
```
export interface IGPIProps {
  shape: any;
  canvasSize: [number, number];
  // COMBAK: why are ctm and dragEvent property here and not in the next interface?? We should separate static and interactive rendering in the near future
  // ctm: DOMMatrix;
  // dragEvent?(id: string, dy: number, dx: number): void;
}

export interface IGPIPropsDraggable extends IGPIProps {
  onClick(e: React.MouseEvent<any>): void;
  ctm: DOMMatrix;
  dragEvent?(id: string, dy: number, dx: number): void;
}
```
* Next, I temporarily removed `draggable` for `Circle`s and removed all drag-related code in that one component. I also made it inherit `IGPIProps` instead.
* In `StaticCanvas`, instead of looking up the `componentMap` (which maps to the draggable types), I only render my simplified version of `Circle` and just output `<g></g>` for everything else.
* Here is the rendered initial state of the tree-venn example:
image
```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" width="100%" height="100%" viewBox="0 0 800 700" data-reactroot="">
    <desc>This diagram was created with Penrose (https://penrose.ink) on 2019-12-08. If you have any suggestions on making this diagram more accessible, please contact us.
    </desc>
    <circle cx="706.9402465820312" cy="258.6477355957031" r="46.937278747558594" fill="#9bda32" fill-opacity="0.5" stroke="#386cd4" stroke-opacity="0.5" stroke-dasharray="" stroke-width="0">
        <title>A.shape</title>
        <desc>Circle representing             <!-- -->A.shape</desc>
    </circle>
    <g></g>
    <circle cx="510.2204284667969" cy="687.2195434570312" r="13.023045539855957" fill="#d83589" fill-opacity="0.5" stroke="#c7965b" stroke-opacity="0.5" stroke-dasharray="" stroke-width="0">
        <title>B.shape</title>
        <desc>Circle representing             <!-- -->B.shape</desc>
    </circle>
    <g></g>
    <circle cx="433.9913024902344" cy="464.3719482421875" r="122.04946899414062" fill="#d2836a" fill-opacity="0.5" stroke="#3b54dc" stroke-opacity="0.5" stroke-dasharray="" stroke-width="0">
        <title>C.shape</title>
        <desc>Circle representing             <!-- -->C.shape</desc>
    </circle>
    <g></g>
    <circle cx="121.85693359375" cy="343.3642883300781" r="18.884334564208984" fill="#ca2c50" fill-opacity="0.5" stroke="#826a22" stroke-opacity="0.5" stroke-dasharray="" stroke-width="0">
        <title>D.shape</title>
        <desc>Circle representing             <!-- -->D.shape</desc>
    </circle>
    <g></g>
    <circle cx="359.079833984375" cy="643.7744445800781" r="100.9706802368164" fill="#d0aec4" fill-opacity="0.5" stroke="#573d6c" stroke-opacity="0.5" stroke-dasharray="" stroke-width="0">
        <title>E.shape</title>
        <desc>Circle representing             <!-- -->E.shape</desc>
    </circle>
    <g></g>
    <circle cx="403.3857727050781" cy="36.21539306640625" r="73.23594665527344" fill="#953551" fill-opacity="0.5" stroke="#c48f62" stroke-opacity="0.5" stroke-dasharray="" stroke-width="0">
        <title>F.shape</title>
        <desc>Circle representing             <!-- -->F.shape</desc>
    </circle>
    <g></g>
    <circle cx="675.4052734375" cy="144.45172119140625" r="23.212879180908203" fill="#4daf2d" fill-opacity="0.5" stroke="#627e30" stroke-opacity="0.5" stroke-dasharray="" stroke-width="0">
        <title>G.shape</title>
        <desc>Circle representing             <!-- -->G.shape</desc>
    </circle>
    <g></g>
</svg>
```

The output looks correct for the circles. Here's the original result:
image

## Next steps

Seems like headless rendering using React SSR is feasible. Here are the main next steps that I have in mind:

1. Clean up the interfaces and shape components to decouple the drag-related logics and shape-rendering ones. Ideally, one can choose to either render a basic, static version of a shape, or an interactive version by supplying event listeners to the component. 
  * Is there a clean way to achieve so without significant refactoring (cc: @maxkrieger)?
  * I was guessing props like `ctm` and `dragEvent` are `Draggable`-specific things, but maybe I missed some details there. @maxkrieger probably has a better idea of why the types are written this way.
2. TODO

**Comment by maxkrieger** [comment]
>   // COMBAK: why are ctm and dragEvent property here and not in the next interface?? We should separate static and interactive rendering in the near future

This was a dumb idea, and I believe it's because I wanted prop-polymorphism since I was firing the `onMouseDown` event on the root shape for some reason, not the `<g>` given for free in `draggable`. I'm refactoring everything now with the assumption that the `<g>` works instead, hopefully I'm right.

**Comment by wodeni** [comment]
Some examples of synthesized geometry Substance programs:
```
$ penrose-synthesizer ../examples/geometry-domain/geometry.dsl --num-programs=10 --max-length=10
Generated new program (synthesized-progs/prog-1.sub):
AutoLabel All
Segment s
Triangle t
RightT(t)
Linelike l
Linelike l1
Linelike l2
Triangle t1
t1 := MkTriangleL(l,l,l)
Point p
Angle a
a := TriangleVertex(p,p,p)
Acute(a)
Linelike l3
Point p1
p1 := Intersection(l,l)
Triangle t2
Square s1
Angle a1
Right(a1)
Linelike l4
Parallel(l, l2)
Generated new program (synthesized-progs/prog-2.sub):
AutoLabel All
Angle a
Obtuse(a)
Linelike l
Generated new program (synthesized-progs/prog-3.sub):
AutoLabel All
Point p
Point p1
Circle c
c := MkCircleD(p,p)
Triangle t
t := MkTriangleP(p1,p,p1)
Circle c1
Point p2
Point p3
p3 := MkLine(p2,p1)
Generated new program (synthesized-progs/prog-4.sub):
AutoLabel All
Triangle t
EquilateralT(t)
Generated new program (synthesized-progs/prog-5.sub):
AutoLabel All
Ray r
Triangle t
Similar(t, t)
Point p
Point p1
Triangle t1
t1 := MkTriangleP(p,p,p1)
Angle a
Obtuse(a)
Linelike l
Linelike l1
Perpendicular(l, l1)
Angle a1
Circle c
c := MkCircleD(p,p1)
Generated new program (synthesized-progs/prog-6.sub):
AutoLabel All
Angle a
Obtuse(a)
Linelike l
Generated new program (synthesized-progs/prog-7.sub):
AutoLabel All
Point p
Segment s
s := MkSegment(p,p)
Triangle t
Triangle t1
Similar(t, t1)
Linelike l
Perpendicular(l, l)
Line l1
Point p1
Circle c
c := MkCircleR(p,p1)
Square s1
Triangle t2
Scalene(t1)
Generated new program (synthesized-progs/prog-8.sub):
AutoLabel All
Linelike l
Generated new program (synthesized-progs/prog-9.sub):
AutoLabel All
Segment s
Generated new program (synthesized-progs/prog-10.sub):
AutoLabel All
Angle a
Obtuse(a)
Angle a1
```

**Comment by hypotext** [comment]
@wodeni Cool! I don't think I've written styles for all of the constructs in the geometry domain program, so I'd check euclidean.sty for what is currently handled. If it's not in there, you might have to add the style (e.g. for an obtuse angle). Otherwise, it looks plausible.

I'd just make sure the arguments to constructors are all distinct (e.g. `MkTriangle(l, l, l)` and `MkTriangleP(p1,p,p1)` won't work).

**Pull request merged**
