### PR TITLE
Add graph domain and graph layout to Penrose

### PR DESCRIPTION
**Pull request by hypotext**
**Not ready for review; this PR description will track progress**

For the figures in the paper, the original graphviz code and graphviz output can be found [here](https://github.com/penrose/TOG-2019/tree/master/Media/CompilerDiagrams)

Programs for this PR can be found [here](https://github.com/penrose/penrose/tree/graph-layout/examples/comp-graph-domain)

Other goal diagrams can be found here: https://github.com/penrose/penrose/issues/319

## Graph layout using a plugin

The plugin is [Dagre](https://github.com/dagrejs/dagre/wiki#using-dagre).

Substance programs
* `one-node.sub`
* `two-nodes.sub`
* `three-nodes.sub`
* `optimization-graph.sub`

Command: `runpenrose comp-graph-domain/optimization-graph.sub comp-graph-domain/comp-graph-plugin.sty comp-graph-domain/comp-graph.dsl`

image

* `computation-graph.sub`

Command: `runpenrose comp-graph-domain/computation-graph.sub comp-graph-domain/comp-graph-plugin.sty comp-graph-domain/comp-graph.dsl`

image

* `dagre-example-graph.sub`

image

### Known issues

- [ ] Arrow-drawing code doesn't account for arrowhead size
- [ ] Label size is not available to plugin, so we use heuristics
- [ ] Text size cannot be changed
- [ ] Investigate `findIntersections` code, which doesn't seem to work (maybe it's messing up the label code that calls it?)

## Pure Penrose graph layout
(does not use plugin)

Command: `runpenrose comp-graph-domain/paper-example-graph.sub comp-graph-domain/comp-graph.sty comp-graph-domain/comp-graph.dsl`

(Note: this is NOT `graph-theory-domain`, which is tracking something else that I don't remember)

Currently goes offscreen

---

# Description

Related issues: #319

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [ ] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

### CODE REVIEW

**Comment by hypotext** [comment]
Hey @wodeni as requested, I added code in the last commit for calculating intersection between a segment and an axis-aligned bounding box, and drawing a segment between the bboxes. It works, as you can see in the screenshots above. 

However, it doesn't yet account for the arrowhead size and how that scales. Since you're the arrowhead czar, can you add that to the code?

**Comment by hypotext** [comment]
actually @wodeni: if you haven't started the arrowhead stuff, I'll write a quick heuristic to deal with it now, so I can tie up loose ends in this PR

**Comment by wodeni** [comment]
> actually @wodeni: if you haven't started the arrowhead stuff, I'll write a quick heuristic to deal with it now, so I can tie up loose ends in this PR

The solution will be very similar to the one noted [here](https://github.com/penrose/penrose/pull/278#issuecomment-549572165). The scaling issue is generally unsolved in SVG markers, so the best you can do is some manual offsets like I did with `Arrow`. For `Path` it's a bit different, maybe just approximate that by taking the last two points on the polyline to compute the direction of the arrow?

**Comment by wodeni** [comment]
Closing this PR due to inactivity (also this PR is on the Haskell version).

**Pull request closed without merging**
