### PR TITLE
Dsll substance modifications

### PR DESCRIPTION
**Pull request by dormaayan**
# Description

Related issues: #95 

This PR adds the following abilities to Substance & DSLL:

1. Prelude option in the DSLL + type checking
2. Substance deconstructors + type checking

# Implementation strategy and design decisions

The most important thing other that obvious changes to the grammar, parser, and type checker is that as a first step after parsing the Substance program, before the type checking I modify now the Substance program AST to include all the prelude statements, and then use the modified AST for the rest of the code.

# Examples with steps to reproduce them

In order to reproduce the Substance deconstructors, run the following:
`runpenrose real-analysis-domain/deconstructors-example.sub real-analysis-domain/test-new-sub.sty real-analysis-domain/real-analysis.dsl`

In order to reproduce prelude you can uncomment the value declarations in `linear-algebra.dsl` and run for example `twoVectors.sub` (full path: `runpenrose linear-algebra-domain/twoVectors.sub linear-algebra-domain/linear-algebra.sty linear-algebra-domain/linear-algebra.dsl`) and you will notice the new vector spaces which were added. In case you will try to use a prelude name in the Substance program, you will get an error.

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran [Haddock](https://github.com/penrose/penrose/wiki/Writing-and-generating-documentation#generating-html-documentation-site) and there were no errors when generating the HTML site
- [x] My changes generate no new warnings
- [ ] New and existing tests pass locally using `stack test`
- [x] My code follows the style guidelines of this project (e.g.: no HLint warnings)

# Open questions

Currently, I didn't implemented yet the built in lists since it is not needed for the current domain. It will be added in the near future, but you can merge now.

### CODE REVIEW

**Comment by dormaayan** [comment]
@hypotext , You can merge this branch to master after reviewing.
Later on today the Syntactic Sugar branch will also be ready for merging to master

**Comment by hypotext** [comment]
In contrast with the other branch, it looks like there's no problem in building this branch:

```
katherineye@kye ~/D/C/penrose> stack build --dry-run --profile
No packages would be unregistered.

Would build:
penrose-0.1.0.2: database=local, source=/Users/katherineye/Desktop/Code/penrose/

No executables to be installed.
```

**Comment by hypotext** [comment]
@dormaayan Sorry for the delay in reviewing.

Can you add the typing rules (and any other grammar/semantics) for the Prelude and the value deconstructors to the design paper, and put screenshots of them here (or refer to them inline in the code)?

That will make it easier for me to review the code, and will ensure that we have all language features documented at a high level in somewhere other than the implementation.

You can see an example of how I documented the Style compiler here (and throughout the file): https://github.com/penrose/penrose/blob/master/src/Style.hs#L1191

**Comment by hypotext** [comment]
Regarding testing: I think we're good to merge this PR (and the other PR) without extensive testing. The testing will come when I use these features in the RA domain (which I will soon!), at which point I might request changes. 🙂

**Comment by hypotext** [comment]
BTW, when using the Prelude with the path I put in the README, I get a bunch of Style warnings that don't occur without the Prelude:

```
Warning: Sub obj 'T1''s field 'sameHeight' is overridden, but was not declared an override
Warning: Sub obj 'T1''s field 'nonIntersect' is overridden, but was not declared an override
Warning: Sub obj 'T''s field 'sameHeight' is overridden, but was not declared an override
Warning: Sub obj 'T''s field 'nonIntersect' is overridden, but was not declared an override
Warning: Sub obj 'U''s field 'sameHeight' is overridden, but was not declared an override
Warning: Sub obj 'U''s field 'nonIntersect' is overridden, but was not declared an override
```

Could be that this is something I should fix in Style, but let me know if the cause of the error seems obviously related to something you added.

**Comment by dormaayan** [comment]
I merge this PR to master as we agreed, but notice it also contain parts of your prior RA work. However there should not be major conflicts

**Pull request merged**
